/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package macromedia;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;

/**
 *
 * @author Helios
 */
public class OrderDetail extends javax.swing.JFrame {

    /**
     * Creates new form OrderDetail
     */
    public OrderDetail() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        scrollPane = new javax.swing.JScrollPane();
        mainContainer = new javax.swing.JPanel();
        formContainer = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNamaItem = new javax.swing.JTextField();
        txtHargaUnit = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtQty = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        scrollDeskripsi = new javax.swing.JScrollPane();
        txtDeskripsi = new javax.swing.JTextArea();
        txtFrek = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtPeriode = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtDiscount = new javax.swing.JTextField();
        tambahOrder = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(204, 204, 204));

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 106, 255));
        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(51, 102, 255));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Next Step");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 106, 255));
        jButton7.setText("Reset");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        scrollPane.setBackground(new java.awt.Color(255, 255, 255));
        scrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        mainContainer.setBackground(new java.awt.Color(204, 204, 204));

        formContainer.setBackground(new java.awt.Color(204, 204, 204));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Nama Item");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Deskripsi");

        txtNamaItem.setBackground(new java.awt.Color(255, 255, 255));

        txtHargaUnit.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Harga Per Unit");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Qty");

        txtQty.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Order Detail");

        txtDeskripsi.setBackground(new java.awt.Color(255, 255, 255));
        txtDeskripsi.setColumns(1);
        txtDeskripsi.setForeground(new java.awt.Color(0, 0, 0));
        txtDeskripsi.setRows(1);
        txtDeskripsi.setTabSize(1);
        txtDeskripsi.setToolTipText("Message");
        scrollDeskripsi.setViewportView(txtDeskripsi);

        txtFrek.setBackground(new java.awt.Color(255, 255, 255));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("Frek");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setText("Periode");

        txtPeriode.setBackground(new java.awt.Color(255, 255, 255));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setText("Discount");

        txtDiscount.setBackground(new java.awt.Color(255, 255, 255));
        txtDiscount.setColumns(6);

        javax.swing.GroupLayout formContainerLayout = new javax.swing.GroupLayout(formContainer);
        formContainer.setLayout(formContainerLayout);
        formContainerLayout.setHorizontalGroup(
            formContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formContainerLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(formContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formContainerLayout.createSequentialGroup()
                        .addGroup(formContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(formContainerLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(398, 398, 398)
                                .addComponent(jLabel8))
                            .addGroup(formContainerLayout.createSequentialGroup()
                                .addComponent(txtNamaItem, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(txtHargaUnit))
                            .addComponent(jLabel7)
                            .addGroup(formContainerLayout.createSequentialGroup()
                                .addGroup(formContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(formContainerLayout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addGap(224, 224, 224)
                                        .addComponent(jLabel17)
                                        .addGap(205, 205, 205)
                                        .addComponent(jLabel18))
                                    .addGroup(formContainerLayout.createSequentialGroup()
                                        .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtFrek, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtPeriode, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(formContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(txtDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(scrollDeskripsi))
                        .addContainerGap(114, Short.MAX_VALUE))
                    .addGroup(formContainerLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        formContainerLayout.setVerticalGroup(
            formContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formContainerLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(formContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8))
                .addGap(6, 6, 6)
                .addGroup(formContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNamaItem, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHargaUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(6, 6, 6)
                .addComponent(scrollDeskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(formContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addGap(6, 6, 6)
                .addGroup(formContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFrek, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(formContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPeriode, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout mainContainerLayout = new javax.swing.GroupLayout(mainContainer);
        mainContainer.setLayout(mainContainerLayout);
        mainContainerLayout.setHorizontalGroup(
            mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(formContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        mainContainerLayout.setVerticalGroup(
            mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainContainerLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(formContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        scrollPane.setViewportView(mainContainer);

        tambahOrder.setBackground(new java.awt.Color(51, 51, 51));
        tambahOrder.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        tambahOrder.setForeground(new java.awt.Color(0, 106, 255));
        tambahOrder.setText("Tambah Order Detail");
        tambahOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tambahOrderMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tambahOrder)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(jButton7)
                        .addGap(642, 642, 642)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 31, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tambahOrder)
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        scrollPane.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        new Create().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        new Summary().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

//    private JPanel mainContainer;
    private int rowCounter = 0;
    private java.util.List<JScrollPane> formList = new java.util.ArrayList<>();
    private void tambahOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambahOrderMouseClicked
        JScrollPane newFormScrollPane = createNewFormContainer();

        // Setup GridBagConstraints for the new form
        GridBagConstraints gbcPanel = new GridBagConstraints();
        gbcPanel.gridx = 0;
        gbcPanel.gridy = rowCounter++;
        gbcPanel.weightx = 1.0;
        gbcPanel.fill = GridBagConstraints.HORIZONTAL;

        System.out.println(newFormScrollPane);

        // Add new form to the main container
        mainContainer.add(newFormScrollPane, gbcPanel);

        // Refresh the container to show the new form
        mainContainer.setMinimumSize(new Dimension(900, 400));
        mainContainer.revalidate();
        mainContainer.repaint();

        // Add the new form to the formList
        formList.add(newFormScrollPane);

        // Optional: Display the total number of forms for debugging
        System.out.println("FormContainer added! Total forms: " + formList.size());
    }//GEN-LAST:event_tambahOrderMouseClicked

    private JScrollPane createNewFormContainer() {
        JPanel formContainer = new JPanel();
        formContainer.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        formContainer.setBackground(Color.WHITE);

        System.out.println("ASDASDJASDHAISODHASDH");
        // Label Order Detail (Atas)
        JLabel orderDetailLabel = new JLabel("Order Detail");
        orderDetailLabel.setFont(new Font("Arial", Font.BOLD, 16));

        GridBagConstraints gbcLabelTop = new GridBagConstraints();
        gbcLabelTop.gridx = 0;
        gbcLabelTop.gridy = 0;
        gbcLabelTop.gridwidth = 2;
        gbcLabelTop.insets = new Insets(10, 5, 5, 5);
        gbcLabelTop.anchor = GridBagConstraints.WEST;
        formContainer.add(orderDetailLabel, gbcLabelTop);
//
//        // Komponen Input
//        JLabel namaItemLabel = new JLabel("Nama Item");
//        JTextField namaItemField = new JTextField(20);
//        JLabel hargaUnitLabel = new JLabel("Harga Per Unit");
//        JTextField hargaUnitField = new JTextField(20);
//        JLabel deskripsiLabel = new JLabel("Deskripsi");
//        JTextArea deskripsiArea = new JTextArea(3, 20);
//        JScrollPane deskripsiScrollPane = new JScrollPane(deskripsiArea);
//        JLabel qtyLabel = new JLabel("Qty");
//        JTextField qtyField = new JTextField(5);
//        JLabel frekLabel = new JLabel("Frek");
//        JTextField frekField = new JTextField(5);
//        JLabel periodeLabel = new JLabel("Periode");
//        JTextField periodeField = new JTextField(5);
//        JLabel discountLabel = new JLabel("Discount");
//        JTextField discountField = new JTextField(5);
//
//        // Tambahkan komponen input ke formContainer dengan GridBagConstraints
//        GridBagConstraints gbcNamaItemLabel = new GridBagConstraints();
//        gbcNamaItemLabel.gridx = 0;
//        gbcNamaItemLabel.gridy = 1;
//        gbcNamaItemLabel.anchor = GridBagConstraints.WEST;
//        formContainer.add(namaItemLabel, gbcNamaItemLabel);
//
//        GridBagConstraints gbcNamaItemField = new GridBagConstraints();
//        gbcNamaItemField.gridx = 1;
//        gbcNamaItemField.gridy = 1;
//        gbcNamaItemField.fill = GridBagConstraints.HORIZONTAL;
//        formContainer.add(namaItemField, gbcNamaItemField);
//
//        GridBagConstraints gbcHargaUnitLabel = new GridBagConstraints();
//        gbcHargaUnitLabel.gridx = 0;
//        gbcHargaUnitLabel.gridy = 2;
//        gbcHargaUnitLabel.anchor = GridBagConstraints.WEST;
//        formContainer.add(hargaUnitLabel, gbcHargaUnitLabel);
//
//        GridBagConstraints gbcHargaUnitField = new GridBagConstraints();
//        gbcHargaUnitField.gridx = 1;
//        gbcHargaUnitField.gridy = 2;
//        gbcHargaUnitField.fill = GridBagConstraints.HORIZONTAL;
//        formContainer.add(hargaUnitField, gbcHargaUnitField);
//
//        GridBagConstraints gbcDeskripsiLabel = new GridBagConstraints();
//        gbcDeskripsiLabel.gridx = 0;
//        gbcDeskripsiLabel.gridy = 3;
//        gbcDeskripsiLabel.anchor = GridBagConstraints.WEST;
//        formContainer.add(deskripsiLabel, gbcDeskripsiLabel);
//
//        GridBagConstraints gbcDeskripsiArea = new GridBagConstraints();
//        gbcDeskripsiArea.gridx = 1;
//        gbcDeskripsiArea.gridy = 3;
//        gbcDeskripsiArea.fill = GridBagConstraints.HORIZONTAL;
//        formContainer.add(deskripsiScrollPane, gbcDeskripsiArea);
//
//        GridBagConstraints gbcQtyLabel = new GridBagConstraints();
//        gbcQtyLabel.gridx = 0;
//        gbcQtyLabel.gridy = 4;
//        gbcQtyLabel.anchor = GridBagConstraints.WEST;
//        formContainer.add(qtyLabel, gbcQtyLabel);
//
//        GridBagConstraints gbcQtyField = new GridBagConstraints();
//        gbcQtyField.gridx = 1;
//        gbcQtyField.gridy = 4;
//        gbcQtyField.anchor = GridBagConstraints.WEST;
//        formContainer.add(qtyField, gbcQtyField);
//
//        GridBagConstraints gbcFrekLabel = new GridBagConstraints();
//        gbcFrekLabel.gridx = 0;
//        gbcFrekLabel.gridy = 5;
//        gbcFrekLabel.anchor = GridBagConstraints.WEST;
//        formContainer.add(frekLabel, gbcFrekLabel);
//
//        GridBagConstraints gbcFrekField = new GridBagConstraints();
//        gbcFrekField.gridx = 1;
//        gbcFrekField.gridy = 5;
//        gbcFrekField.anchor = GridBagConstraints.WEST;
//        formContainer.add(frekField, gbcFrekField);
//
//        GridBagConstraints gbcPeriodeLabel = new GridBagConstraints();
//        gbcPeriodeLabel.gridx = 0;
//        gbcPeriodeLabel.gridy = 6;
//        gbcPeriodeLabel.anchor = GridBagConstraints.WEST;
//        formContainer.add(periodeLabel, gbcPeriodeLabel);
//
//        GridBagConstraints gbcPeriodeField = new GridBagConstraints();
//        gbcPeriodeField.gridx = 1;
//        gbcPeriodeField.gridy = 6;
//        gbcPeriodeField.anchor = GridBagConstraints.WEST;
//        formContainer.add(periodeField, gbcPeriodeField);
//
//        GridBagConstraints gbcDiscountLabel = new GridBagConstraints();
//        gbcDiscountLabel.gridx = 0;
//        gbcDiscountLabel.gridy = 7;
//        gbcDiscountLabel.anchor = GridBagConstraints.WEST;
//        gbcDiscountLabel.fill = GridBagConstraints.HORIZONTAL;
//        formContainer.add(discountLabel, gbcDiscountLabel);
//
//        GridBagConstraints gbcDiscountField = new GridBagConstraints();
//        gbcDiscountField.gridx = 1;
//        gbcDiscountField.gridy = 7;
//        gbcDiscountField.anchor = GridBagConstraints.WEST;
//        formContainer.add(discountField, gbcDiscountField);
//
//        // Label Order Detail (Bawah)
//        JLabel orderDetailLabelBottom = new JLabel("Order Detail");
//        orderDetailLabelBottom.setFont(new Font("Arial", Font.BOLD, 16));
//        GridBagConstraints gbcLabelBottom = new GridBagConstraints();
//        gbcLabelBottom.gridx = 0;
//        gbcLabelBottom.gridy = 8; // Baris terakhir
//        gbcLabelBottom.gridwidth = 2;
//        gbcLabelBottom.insets = new Insets(5, 5, 10, 5);
//        gbcLabelBottom.anchor = GridBagConstraints.WEST;
//        formContainer.add(orderDetailLabelBottom, gbcLabelBottom);

        // Tambahkan formContainer ke JScrollPane
        JScrollPane scrollPane = new JScrollPane(formContainer);

        return scrollPane;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderDetail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel formContainer;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel mainContainer;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JScrollPane scrollDeskripsi;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JLabel tambahOrder;
    private javax.swing.JTextArea txtDeskripsi;
    private javax.swing.JTextField txtDiscount;
    private javax.swing.JTextField txtFrek;
    private javax.swing.JTextField txtHargaUnit;
    private javax.swing.JTextField txtNamaItem;
    private javax.swing.JTextField txtPeriode;
    private javax.swing.JTextField txtQty;
    // End of variables declaration//GEN-END:variables
}
